In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/user/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/User

In [4]:
null_vector=np.zeros(10)

In [5]:
list1=[5,7,3,9,1,4]

In [6]:
list_array=np.array(list1)

In [7]:
list_array

array([5, 7, 3, 9, 1, 4])

In [8]:
len(list1)

6

In [9]:
# How to get the documentation of the numpy add function from the command line
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [10]:
# Create a null vector of size 10 but the fifth value which is 1
import numpy as np
N= np.zeros(10)
N[5]=1
print(N)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49
import numpy as np
N=np.arange(10,50)
print(N)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#Reverse a vector (first element becomes last)
import numpy as np
N=np.arange(10,50)
N=N[::-1]
print(N)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
N=np.arange(0,9).reshape(3,3)
print(N)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
NZ=np.nonzero([1,2,0,0,4,0])
print(NZ)


(array([0, 1, 4], dtype=int64),)


In [15]:
#Create a 3x3 identity matrix
import numpy as np
NI=np.eye(3)
print(NI)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#Create a 3x3x3 array with random values
import numpy as np
NU=np.random.uniform((3,3,3))
print(NU)

[2.97609506 2.61913188 1.68541224]


In [17]:
#Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
NR=np.random.random((10,10))
Nmin,Nmax=N.min(),N.max()
print('Nmin-',Nmin,' ','Nmax-',Nmax)

Nmin- 0   Nmax- 8


In [18]:
#Create a random vector of size 30 and find the mean value
import numpy as np
N=np.random.random(10)
m=N.mean()
print(m)

0.49682008576189113


In [19]:
#Create a 2d array with 1 on the border and 0 inside
import numpy as np
N=np.ones((10,10))
N[1:-1,1:-1]=0
print(N)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
#How to add a border (filled with 0's) around an existing array?
import numpy as np
N=np.ones((5,5))
N=np.pad(N,pad_width=1,mode='constant',constant_values=0)
print(N)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [21]:
#How to add a border (filled with 0's) around an existing array?
import numpy as np
N=np.ones((5,5))
N[:,[0,-1]]=0
N[[0,-1],:]=0
print(N)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#What is the result of the following expression?
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [23]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
import numpy as np
N=np.diag(1+np.arange(4),k=-1)
print(N)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [24]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
N=np.zeros((8,8),dtype=int)
N[1::2,::2]=1
N[::2,1::2]=1
print(N)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [26]:
#Create a checkerboard 8x8 matrix using the tile function
import numpy as np
N=np.tile( np.array([[0,1],[1,0]]), (4,4))
print(N)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#Normalize a 5x5 random matrix
import numpy as np
N=np.random.random((5,5))
N=(N - np.mean (N)) / (np.std (N))
print(N)

[[ 1.03535601  0.09431829 -1.14381597  1.57595865 -0.93448693]
 [-1.17984519 -1.1523158   0.65905485 -0.88431614  0.43047997]
 [ 0.84454743 -1.28407579  1.72624109 -0.29148521  0.90047944]
 [-0.71878427 -0.88919089  0.36242679 -0.65063501 -1.27819849]
 [ 0.72825027 -0.86678172  0.05354588  1.51837837  1.34489438]]


In [28]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
import numpy as np
color=np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [29]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
N=np.dot(np.random.random((5,3)),np.random.random((3,2)))
print(N)

[[0.17807161 0.86313014]
 [0.12538582 0.3948189 ]
 [0.44205267 1.52615957]
 [0.41440995 1.41734127]
 [0.24250231 0.7542196 ]]


In [30]:
#Given a 1D array, negate all elements which are between 3 and 8, in place
import numpy as np
N=np.arange(11)
N[(3<N)&(N<8)]*=-1
print(N)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [31]:
#What is the output of the following script?
import numpy
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [32]:
#Consider an integer vector Z, which of these expressions are legal?
import numpy
from numpy import *
Z=np.random.random()
print(Z**Z)
#(2 << Z >> 2)
Z=(Z <- Z)
print(1j*Z)
Z=(Z/1/1)
print(Z<Z>Z)

0.6924109546965251
0j
False


In [33]:
#What are the result of the following expressions?
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


In [34]:
#How to round away from zero a float array ?
import numpy as np
N=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(N)), N))

[-9.  3. -9. 10.  2.  9. -6. -1. -5.  7.]


In [35]:
#How to find common values between two arrays?
import numpy as np
N1=np.random.randint(0,10,10)
print(N1)
N2=np.random.randint(0,10,10)
print(N2)
print(np.intersect1d(N1,N2))

[3 9 6 7 9 8 0 5 7 2]
[5 0 4 0 1 2 7 9 3 2]
[0 2 3 5 7 9]


In [36]:
#How to ignore all numpy warnings (not recommended)?
import numpy as np
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [37]:
#Is the following expressions true?
import numpy as np
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [38]:
#How to get the dates of yesterday, today and tomorrow?
import numpy as np
yesterday=np.datetime64('today') - np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today') + np.timedelta64(1)

In [39]:
#How to get all the dates corresponding to the month of July 2016?
import numpy as np
N=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(N)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [40]:
#How to compute ((A+B)*(-A/2)) in place (without copy)?
import numpy as np
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [41]:
#Extract the integer part of a random array of positive numbers using 4 different methods
import numpy as np
N=np.random.uniform(0,10,10)
print(N - N%1)
print(N // 1)
print(np.floor(N))
print(N.astype(int))
print(np.trunc(N))

[3. 8. 2. 9. 6. 7. 3. 1. 8. 4.]
[3. 8. 2. 9. 6. 7. 3. 1. 8. 4.]
[3. 8. 2. 9. 6. 7. 3. 1. 8. 4.]
[3 8 2 9 6 7 3 1 8 4]
[3. 8. 2. 9. 6. 7. 3. 1. 8. 4.]


In [42]:
#Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
N=np.zeros((5,5))
N+=np.arange(5)
print(N)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [43]:
#Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
N=np.tile(np.arange(0, 5), (5,1))
print(N)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [44]:
#Consider a generator function that generates 10 integers and use it to build an array 
import numpy as np
def generate():
    for x in range(10):
        yield x
N=np.fromiter(generate(),dtype=float,count=-1)
print(N)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [45]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
N=np.linspace(0,1,11,endpoint=False)[1:]
print(N)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [46]:
#Create a random vector of size 10 and sort it
import numpy as np
N=np.random.random(10)
N.sort()
print(N)

[0.0756972  0.1721663  0.2093749  0.44075608 0.51329694 0.54375864
 0.63845091 0.80617535 0.80912756 0.87949798]


In [47]:
#How to sum a small array faster than np.sum?
import numpy as np
N=np.arange(10)
np.add.reduce(N)

45

In [48]:
#Consider two random array A and B, check if they are equal
import numpy as np
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
E=np.allclose(A,B)
print(E)
E=np.array_equal(A,B)
print(E)

False
False


In [49]:
#Make an array immutable (read-only)
import numpy as np
N=np.zeros(10)
N.flags.writeable=False
#N[0]=1

In [50]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
import numpy as np
N=np.random.random((10,2))
X,Y=N[:,0], N[:,1]
P=np.sqrt(X**2+Y**2)
Q=np.arctan2(Y,X)
print(P)
print(Q)

[1.04411709 0.75376831 1.02221392 0.51955855 0.72657062 0.82464962
 1.19362321 0.16980079 0.97763468 0.81377263]
[1.16660387 1.02255531 0.83858724 0.8588932  0.2176791  0.95324034
 0.6149958  0.05697802 0.92009976 0.04256509]


In [51]:
#Create random vector of size 10 and replace the maximum value by 0
import numpy as np
N=np.random.random(10)
N[N.argmax()] = 0
print(N)

[0.77286769 0.86900425 0.79231981 0.57150802 0.1753284  0.56806263
 0.40610368 0.47609455 0.         0.13882111]


In [52]:
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
import numpy as np
N=np.zeros((5,5), [('x',float),('y',float)])
N['x'], N['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(N)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [53]:
#Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
import numpy as np
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [54]:
#Print the minimum and maximum representable value for each numpy scalar type (★★☆)
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [55]:
#How to print all the values of an array?
import numpy as np
np.set_printoptions(threshold=float("inf"))
N=np.zeros((40,40))
print(N)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
#How to find the closest value (to a given scalar) in a vector?
import numpy as np
N=np.arange(100)
u=np.random.uniform(0,100)
index=(np.abs(N-u)).argmin()
print(N[index])

87


In [57]:
#Create a structured array representing a position (x,y) and a color (r,g,b)
import numpy as np
N=np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(N)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [58]:
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances
import numpy as np
N=np.random.random((10,2))
X,Y=np.atleast_2d(N[:,0], N[:,1])
S=np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(S)
import scipy
import scipy.spatial
N=np.random.random((10,2))
S=scipy.spatial.distance.cdist(N,N)
print(S)

[[0.         0.36179021 0.39962194 0.61044546 0.68827429 0.79342883
  0.23186991 0.85555324 0.82125567 0.46779426]
 [0.36179021 0.         0.48704214 0.6267918  0.46410921 0.44630848
  0.22362979 0.64915876 0.58262977 0.23514273]
 [0.39962194 0.48704214 0.         0.21344814 0.46557576 0.89780863
  0.54283565 0.57490213 0.58199269 0.7069417 ]
 [0.61044546 0.6267918  0.21344814 0.         0.41749327 0.98104089
  0.73006416 0.4572402  0.49759813 0.86009799]
 [0.68827429 0.46410921 0.46557576 0.41749327 0.         0.64213979
  0.66790654 0.18505838 0.13301536 0.67304093]
 [0.79342883 0.44630848 0.89780863 0.98104089 0.64213979 0.
  0.59024914 0.78456967 0.68961079 0.3741745 ]
 [0.23186991 0.22362979 0.54283565 0.73006416 0.66790654 0.59024914
  0.         0.85124821 0.79349986 0.23939312]
 [0.85555324 0.64915876 0.57490213 0.4572402  0.18505838 0.78456967
  0.85124821 0.         0.09613036 0.85505786]
 [0.82125567 0.58262977 0.58199269 0.49759813 0.13301536 0.68961079
  0.79349986 0.09613

In [59]:
#How to convert a float (32 bits) array into an integer (32 bits) in place?
import numpy as np
N=(np.random.rand(10)*100).astype(np.float32)
Y=N.view(np.int32)
Y[:]=N
print(Y)

[82 39 51 37 69 92 97 51 63 61]


In [60]:
#How to read the following file?
import numpy as np
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
N=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(N)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [61]:
#What is the equivalent of enumerate for numpy arrays?
import numpy as np
N=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(N):
    print(index, value)
for index in np.ndindex(N.shape):
    print(index, N[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [62]:
#Generate a generic 2D Gaussian-like array
import numpy as np
X, Y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
S=np.sqrt(X*X+Y*Y)
sig,mu=1.0,0.0
E=np.exp(-( (S-mu)**2 / ( 2.0 * sig**2 ) ) )
print(E)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [63]:
#How to randomly place p elements in a 2D array? 
import numpy as np
n=10
p=3
N=np.zeros((n,n))
np.put(N, np.random.choice(range(n*n), p, replace=False),1)
print(N)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
#Subtract the mean of each row of a matrix
import numpy as np
X=np.random.rand(5, 10)
Y=X-X.mean(axis=1,keepdims=True)
Y=X-X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.32162085 -0.15266831  0.29502668  0.24269985 -0.05432954 -0.13796681
  -0.13648196 -0.36778703  0.01922978 -0.02934351]
 [-0.26038742  0.3158304  -0.25365445  0.14450626 -0.27773523  0.15220814
   0.04868006 -0.07243585 -0.38834038  0.59132848]
 [ 0.05646113  0.35679935 -0.27394244  0.42448261 -0.17977404  0.27621399
   0.20554802 -0.07102653 -0.37328643 -0.42147566]
 [-0.1634396  -0.28202447  0.16738195  0.03850181  0.39532361 -0.32650067
  -0.0061828   0.298498    0.11650546 -0.23806329]
 [ 0.00949316 -0.20005761  0.24875916 -0.08409104 -0.46471372  0.09941953
  -0.49672872  0.29981624  0.2730481   0.3150549 ]]


In [65]:
#How to sort an array by the nth column?
import numpy as np
N=np.random.randint(0,10,(3,3))
print(N)
print(N[N[:,1].argsort()])

[[7 8 9]
 [6 8 8]
 [2 5 2]]
[[2 5 2]
 [7 8 9]
 [6 8 8]]


In [66]:
#How to tell if a given 2D array has null columns?
import numpy as np
N=np.random.randint(0,3,(3,10))
print((~N.any(axis=0)).any())

True


In [67]:
#Find the nearest value from a given value in an array (★★☆)
N=np.random.uniform(0,1,10)
n=0.5
F=N.flat[np.abs(N-n).argmin()]
print(F)

0.47360173475344924


In [68]:
#Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
import numpy as np
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it: z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [69]:
#Create an array class that has a name attribute
import numpy as np
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info=getattr(obj,'name',"no name")
N=NamedArray(np.arange(10), "range_10")
print(N.name)

range_10


In [70]:
#Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
import numpy as np
N=np.ones(10)
I=np.random.randint(0,len(N),20)
N+=np.bincount(I,minlength=len(N))
print(N)

[2. 4. 2. 2. 3. 1. 5. 3. 3. 5.]


In [71]:
#Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 6. 4. 1. 2. 3. 3. 2.]


In [72]:
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
import numpy as np
X=[1,2,3,4,5,6]
I=[1,3,9,3,4,1]
B=np.bincount(I,X)
print(B)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [73]:
#Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
import numpy as np
w,h=256,256
I=np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors=np.unique(I.reshape(-1,3),axis=0)
n=len(colors)
print(n)


64


In [74]:
#Considering a four dimensions array, how to get sum over the last two axis at once?
import numpy as np
A=np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 61 53 29]
 [41 48 15 65]
 [48 48 43 36]]
[[61 61 53 29]
 [41 48 15 65]
 [48 48 43 36]]


In [75]:
#Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
import numpy as np
U=np.random.uniform(0,1,100)
R=np.random.randint(0,10,100)
U_sums=np.bincount(R,weights=U)
U_counts=np.bincount(R)
U_means=U_sums/U_counts
print(U_means)
import pandas as pd
print(pd.Series(U).groupby(R).mean())

[0.43576897 0.55818525 0.54246085 0.54739127 0.48335271 0.4248411
 0.5593571  0.51680088 0.57070232 0.50220212]
0    0.435769
1    0.558185
2    0.542461
3    0.547391
4    0.483353
5    0.424841
6    0.559357
7    0.516801
8    0.570702
9    0.502202
dtype: float64


In [76]:
#How to get the diagonal of a dot product?
import numpy as np
A=np.random.uniform(0,1,(5,5))
B=np.random.uniform(0,1,(5,5))
D1=np.diag(np.dot(A, B))
print(D1)
D2=np.sum(A * B.T, axis=1)
print(D2)
D3=np.einsum("ij,ji->i", A, B)
print(D3)

[0.38419517 0.56432175 0.96601224 0.88874069 1.95033775]
[0.38419517 0.56432175 0.96601224 0.88874069 1.95033775]
[0.38419517 0.56432175 0.96601224 0.88874069 1.95033775]


In [77]:
#Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
import numpy as np
N=np.array([1,2,3,4,5])
nz=3
N0=np.zeros(len(N)+(len(N)-1)*(nz))
N0[::nz+1]=N
print(N0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [78]:
#Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
import numpy as np
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [79]:
#How to swap two rows of an array?
import numpy as np
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [80]:
#Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
import numpy as np
faces=np.random.randint(0,100,(10,3))
F=np.roll(faces.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G=np.unique(G)
print(G)

[( 2, 76) ( 2, 99) ( 9, 41) ( 9, 42) ( 9, 52) ( 9, 68) (13, 24) (13, 92)
 (21, 22) (21, 48) (22, 48) (24, 92) (41, 42) (43, 67) (43, 91) (46, 52)
 (46, 99) (52, 68) (52, 99) (53, 58) (53, 99) (55, 70) (55, 85) (58, 99)
 (63, 66) (63, 79) (66, 79) (67, 91) (70, 85) (76, 99)]


In [81]:
#Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
import numpy as np
C=np.bincount([1,1,2,3,4,4,6])
A=np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [82]:
#How to compute averages using a sliding window over an array?
import numpy as np
def moving_average(a,n=3):
    ret=np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n
N=np.arange(20)
print(moving_average(N,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [83]:
#Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
import numpy as np
from numpy.lib import stride_tricks
def rolling(a, window):
    shape=(a.size-window+1,window)
    strides=(a.strides[0],a.strides[0])
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
N=rolling(np.arange(10),3)
print(N)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [84]:
#How to negate a boolean, or to change the sign of a float inplace?
import numpy as np
N=np.random.randint(0,2,100)
np.logical_not(N,out=N)
N=np.random.uniform(-1.0,1.0,100)
np.negative(N,out=N)

array([-0.40827545,  0.9307427 ,  0.39974701,  0.81847908,  0.26375162,
        0.50731326, -0.33117766,  0.78816151,  0.22235923,  0.13997114,
        0.35429464, -0.19227256, -0.33122709, -0.08753682, -0.73094151,
        0.66938864,  0.28233049,  0.33698686,  0.66261716, -0.16683681,
        0.80467882, -0.98604109, -0.64308283,  0.25480111,  0.10819003,
        0.59525322, -0.15653985,  0.36279166,  0.40048912,  0.95840946,
       -0.23452916,  0.46620857,  0.04938147,  0.34987943,  0.5771779 ,
       -0.34132752,  0.00398375,  0.82250524, -0.94547121, -0.12043366,
        0.5747651 , -0.40669195,  0.1671652 ,  0.59514572, -0.30356617,
        0.63883011,  0.18376032,  0.08609317, -0.56842404,  0.26653349,
        0.39161397,  0.66922492, -0.53486043, -0.29798323,  0.85904544,
        0.27850443,  0.45877602, -0.82039307,  0.99652436,  0.26949204,
        0.96039305,  0.79975834, -0.60433211, -0.66209576, -0.04978104,
        0.2045449 , -0.37802268, -0.20296772,  0.46806742,  0.35

In [85]:
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
import numpy as np
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[0.86318528 3.2939342  3.87191813 4.18821679 7.9330403  3.31989974
 4.14835389 3.54338271 9.62673842 6.47718668]


In [86]:
#Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 
import numpy as np
P0=np.random.uniform(-10, 10, (10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[9.87975372e+00 5.71740170e+00 3.60861303e-01 3.80604468e+00
  3.36651239e+00 6.65848351e+00 4.67125322e+00 1.49714017e+01
  2.21374998e+00 6.78234574e-01]
 [3.44623301e+00 8.07520967e-01 5.20322856e+00 2.57946935e+00
  2.95342703e+00 2.19177315e+00 5.61954835e+00 1.22648367e+01
  2.98283696e+00 5.58640125e+00]
 [6.49266702e+00 1.40780063e+00 4.01188770e+00 5.48012725e-01
  7.98406491e-01 5.73020501e+00 7.45632126e+00 1.54705011e+01
  5.80196517e-01 2.02128974e+00]
 [9.55796016e+00 4.23910252e+00 1.23677383e+01 1.57801429e+01
  1.33590079e+01 1.08624120e+01 1.07149521e+00 1.35234395e+00
  1.66044284e+01 1.90171471e+01]
 [1.02077035e+01 5.17930555e+00 1.53099011e-02 4.17898716e+00
  3.30577698e+00 7.53680492e+00 5.66779975e+00 1.59888808e+01
  2.98253613e+00 1.39229706e-01]
 [3.64208693e+00 1.54205481e+00 7.12531920e+00 2.23469930e+00
  3.97475435e+00 4.39015647e+00 8.90281899e+00 1.51351576e+01
  1.22738167e+00 3.63881946e+00]
 [6.42706667e+00 7.35611101e+00 9.51477436e-01 1.21955704e

In [87]:
#Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
import numpy as np
N=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)

R=np.ones(shape, dtype=Z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Ns=np.array(list(Z.shape)).astype(int)

R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.array(list(shape)).astype(int)
N_start=(P-Rs//2)
N_stop=(P+Rs//2)+Rs%2

R_start=(R_start - np.minimum(N_start,0)).tolist()
N_start=(np.maximum(N_start,0)).tolist()
R_stop=np.maximum(R_start, (R_stop - np.maximum(N_stop-Ns,0))).tolist()
N_stop=(np.minimum(N_stop,Ns)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
n=[slice(start,stop) for start,stop in zip(N_start,N_stop)]
R[r]=N[n]
print(N)
print(R)

[[3 6 7 2 0 6 6 7 6 8]
 [2 0 6 4 8 8 3 3 5 0]
 [2 1 6 6 5 7 4 3 8 0]
 [1 5 8 8 4 5 5 3 7 2]
 [0 4 8 1 9 3 5 5 6 5]
 [6 7 9 9 9 0 7 6 6 2]
 [5 9 6 7 9 5 8 9 5 1]
 [4 3 0 5 5 6 6 2 1 7]
 [6 1 6 2 7 8 5 3 4 0]
 [3 7 1 0 5 2 2 3 0 4]]
[[0. 0. 0. 0. 0.]
 [0. 3. 6. 7. 2.]
 [0. 2. 0. 6. 4.]
 [0. 2. 1. 6. 6.]
 [0. 1. 5. 8. 8.]]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [88]:
#Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
import numpy as np
N=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(N,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [89]:
#Compute a matrix rank
import numpy as np
N=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(N)
rank=np.sum(S > 1e-10)
print(rank)

10


In [90]:
#How to find the most frequent value in an array?
N=np.random.randint(0,10,50)
print(np.bincount(N).argmax())

0


In [91]:
#Extract all the contiguous 3x3 blocks from a random 10x10 matrix
import numpy as np
N=+np.random.randint(0,5,(10,10))
n=+3
i=+1+(N.shape[0]-3)
j=+1+(N.shape[1]-3)
C=+stride_tricks.as_strided(N,shape=(i,j,n,n),strides=N.strides+N.strides)
print(C)

[[[[1 4 4]
   [2 2 3]
   [1 3 4]]

  [[4 4 2]
   [2 3 2]
   [3 4 3]]

  [[4 2 3]
   [3 2 0]
   [4 3 1]]

  [[2 3 2]
   [2 0 2]
   [3 1 4]]

  [[3 2 1]
   [0 2 0]
   [1 4 2]]

  [[2 1 2]
   [2 0 2]
   [4 2 1]]

  [[1 2 1]
   [0 2 2]
   [2 1 3]]

  [[2 1 1]
   [2 2 1]
   [1 3 1]]]


 [[[2 2 3]
   [1 3 4]
   [1 1 3]]

  [[2 3 2]
   [3 4 3]
   [1 3 3]]

  [[3 2 0]
   [4 3 1]
   [3 3 3]]

  [[2 0 2]
   [3 1 4]
   [3 3 1]]

  [[0 2 0]
   [1 4 2]
   [3 1 2]]

  [[2 0 2]
   [4 2 1]
   [1 2 1]]

  [[0 2 2]
   [2 1 3]
   [2 1 3]]

  [[2 2 1]
   [1 3 1]
   [1 3 0]]]


 [[[1 3 4]
   [1 1 3]
   [1 2 1]]

  [[3 4 3]
   [1 3 3]
   [2 1 1]]

  [[4 3 1]
   [3 3 3]
   [1 1 1]]

  [[3 1 4]
   [3 3 1]
   [1 1 0]]

  [[1 4 2]
   [3 1 2]
   [1 0 3]]

  [[4 2 1]
   [1 2 1]
   [0 3 2]]

  [[2 1 3]
   [2 1 3]
   [3 2 1]]

  [[1 3 1]
   [1 3 0]
   [2 1 3]]]


 [[[1 1 3]
   [1 2 1]
   [1 0 4]]

  [[1 3 3]
   [2 1 1]
   [0 4 0]]

  [[3 3 3]
   [1 1 1]
   [4 0 3]]

  [[3 3 1]
   [1 1 0]
   [0 3 2]]

  [[3 1 2]
   

In [92]:
#Create a 2D array subclass such that Z[i,j] == Z[j,i] 
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j=index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S=symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)

[[ 1  8  7 15  9]
 [ 8  7 11  9  5]
 [ 7 11  9 42 10]
 [15  9 42  2  9]
 [ 9  5 10  9  0]]


In [93]:
#Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
import numpy as np
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [94]:
#Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
import numpy as np
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [95]:
#How to implement the Game of Life using numpy arrays?
import numpy as np
def iterate(Z):
    # Count neighbours
    N=(Z[0:-2,0:-2]+Z[0:-2,1:-1]+Z[0:-2,2:]+Z[1:-1,0:-2]+Z[1:-1,2:]+Z[2:,0:-2]+Z[2:,1:-1]+Z[2:,2:])
    birth=(N==3) & (Z[1:-1,1:-1]==0)
    survive=((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...]=0
    Z[1:-1,1:-1][birth | survive]=1
    return Z

N=np.random.randint(0,2,(50,50))
for i in range(100): N=iterate(N)
print(N)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0

In [96]:
#How to get the n largest values of an array
import numpy as np
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


In [97]:
#Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
import numpy as np
def cartesian(arrays):
    arrays=[np.asarray(a) for a in arrays]
    shape=(len(x) for x in arrays)
    ix=np.indices(shape, dtype=int)
    ix=ix.reshape(len(arrays), -1).T
    for n,arr in enumerate(arrays):
        ix[:,n]=arrays[n][ix[:,n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [98]:
#How to create a record array from a regular array?
import numpy as np
N=np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R=np.core.records.fromarrays(N.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [99]:
#Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 
import numpy as np
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 6 7]


In [100]:
import numpy as np
#Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.76 s ± 22.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
232 ms ± 27.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
148 ms ± 2.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [106]:
#Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 
import numpy as np
N=np.random.randint(0,5,(10,3))
print(N)
E=np.all(N[:,1:]==N[:,:-1], axis=1)
U=N[~E]
print(U)
U=N[N.max(axis=1)!=N.min(axis=1),:]
print(U)

[[1 0 4]
 [0 1 1]
 [2 1 4]
 [0 2 4]
 [2 2 3]
 [3 4 2]
 [4 1 3]
 [2 1 1]
 [0 2 1]
 [0 2 2]]
[[1 0 4]
 [0 1 1]
 [2 1 4]
 [0 2 4]
 [2 2 3]
 [3 4 2]
 [4 1 3]
 [2 1 1]
 [0 2 1]
 [0 2 2]]
[[1 0 4]
 [0 1 1]
 [2 1 4]
 [0 2 4]
 [2 2 3]
 [3 4 2]
 [4 1 3]
 [2 1 1]
 [0 2 1]
 [0 2 2]]


In [107]:
#Convert a vector of ints into a matrix binary representation
import numpy as np
I=np.array([0,1,2,3,15,16,32,64,128])
B=((I.reshape(-1,1)&(2**np.arange(8)))!=0).astype(int)
print(B[:,::-1])
I=np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [108]:
#Given a two dimensional array, how to extract unique rows?
import numpy as np
N=np.random.randint(0,2,(6,3))
T=np.ascontiguousarray(N).view(np.dtype((np.void, N.dtype.itemsize*N.shape[1])))
_, idx=np.unique(T,return_index=True)
uN=N[idx]
print(uN)
uN=np.unique(N, axis=0)
print(uN)

[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [110]:
#Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
import numpy as np
A=np.random.uniform(0,1,10)
B=np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.09552553, 0.22100768, 0.1154313 , 0.10738894, 0.13899619,
        0.15853621, 0.22600934, 0.00410606, 0.04348232, 0.18601838],
       [0.38947408, 0.90108647, 0.47063333, 0.43784326, 0.56671148,
        0.64637952, 0.92147909, 0.01674112, 0.17728493, 0.75842907],
       [0.22563206, 0.52202189, 0.27264964, 0.25365353, 0.32831011,
        0.37446379, 0.53383584, 0.00969855, 0.10270559, 0.43937689],
       [0.06691918, 0.15482409, 0.08086391, 0.07522994, 0.097372  ,
        0.11106051, 0.15832794, 0.00287645, 0.03046098, 0.13031279],
       [0.22833983, 0.52828659, 0.27592166, 0.25669759, 0.33225011,
        0.37895768, 0.54024233, 0.00981494, 0.10393814, 0.44464979],
       [0.20655976, 0.47789627, 0.24960303, 0.23221263, 0.30055861,
        0.34281101, 0.48871161, 0.00887874, 0.09402406, 0.40223711],
       [0.34185034, 0.79090429, 0.41308568, 0.38430509, 0.49741568,
        0.56734215, 0.80880337, 0.01469406, 0.15560706, 0.66569061],
       [0.4171292 , 0.96506931, 0.5040512

In [113]:
#Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
import numpy as np
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)

dr=(np.diff(x)**2+np.diff(y)**2)**.5 
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)               
r_int=np.linspace(0,r.max(),200) 
x_int=np.interp(r_int,r,x)      
y_int=np.interp(r_int,r,y)
print(x_int,y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

In [115]:
#Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
import numpy as np
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1)==0, axis=-1)
M&=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


In [116]:
#Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 
import numpy as np
X=np.random.randn(100)
N=1000
idx=np.random.randint(0,X.size,(N,X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means,[2.5, 97.5])
print(confint)

[-0.2473623  0.2073631]
